# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Tweedle's website
author: David Tweedle
email: david.tweedle@sta.uwi.edu

description: > # ignore until show_excerpts
   Canadian person living in Trinidad.
show_excerpts: false
github_username: davidtweedle
repository: davidtweedle/davidtweedle.github.io

header_pages:
  - index.md
  - research.md
  - teaching.md
  - courses.md
  - links.md

include:
  - assets
  - courses
  - courses/math-2400
  - courses/math-3273
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima
